### PR TITLE
Implement batch_det function

### PR DESCRIPTION
**Pull request by takuseno**
:warning: DO NOT MERGE before #130 because `batch_det` internally uses `batch_inv` and some new `cublas` function.

I've confirmed that the unit test has passed.

https://github.com/sony/nnabla/pull/366

@TE-TakuyaNarihira @TE-AkioHayakawa

### CODE REVIEW

**Comment by TE-TakuyaNarihira** [comment]
Hi @takuseno. Sorry for our late response. Could you format code of your changes (including #130, sony/nnabla#351, sony/nnabla#366)? You know how to do it?

**Comment by takuseno** [comment]
Hi, @TE-TakuyaNarihira san. I'll merge all changes related to this :)

**Comment by takuseno** [comment]
Hi, @TE-TakuyaNarihira san. I've applied the latest master to those branches as well as applying auto format. Thank you for reviewing my codes!

**Comment by takuseno** [comment]
@TE-AkioHayakawa 
I've created a squashed version of PR as #194 . If you prefer the new version, I'd like you to see it :)

**Pull request closed without merging**
